<%@ Page Language="C#" AutoEventWireup="true" CodeFile="editElections.aspx.cs" Inherits="editElections" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>>E-POLLING SYSTEM - Edit Elections</title>
    <link href="Content/fonts.googleapis.com" rel="stylesheet" type="text/css" />
  <link href="Content/materialize.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="Content/icon.css" /></head>
<body>
    <form id="form1" runat="server">
        <!--Nav bar-->
        <nav class="teal" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" href="Default.aspx" class="brand-logo">E-POLLING</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="addElections.aspx">ADD ELECTIONS</a></li>
                    <li><a href="editElections.aspx">EDIT ELECTIONS</a></li>
                    <li><a href="addCandidates.aspx">ADD CANDIDATES</a></li>
                     <li style="text-transform:uppercase;">
                    <asp:LoginStatus ID="LoginStatus2" runat="server"/></li>
                </ul>

                
            </div>
        </nav>
        <!--Nav bar End-->

        <br /> <br />
        <div class="container">
            <h4><strong>EDIT YOUR ELECTIONS HERE:</strong></h4>
            <div class="row">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                <asp:BoundField DataField="title" HeaderText="STATE" SortExpression="title" />
                <asp:BoundField DataField="starttime" HeaderText="START" SortExpression="starttime" />
                <asp:BoundField DataField="endtime" HeaderText="END" SortExpression="endtime" />
                <asp:BoundField DataField="descriptionelection" HeaderText="TITLE/DESCRIPTION" SortExpression="descriptionelection" />
            </Columns>
                                    <EditRowStyle BackColor="#7C6F57" />
                <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#E3EAEB" />
                <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F8FAFA" />
                <SortedAscendingHeaderStyle BackColor="#246B61" />
                <SortedDescendingCellStyle BackColor="#D4DFE1" />
                <SortedDescendingHeaderStyle BackColor="#15524A" />
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:votingConnectionString3 %>" ProviderName="System.Data.SqlClient" 
            SelectCommand="SELECT [id], [title], [starttime], [endtime], [descriptionelection] FROM [elections]"
            UpdateCommand = "UPDATE elections SET title = @title, starttime = @starttime, endtime = @endtime, descriptionelection = @descriptionelection where id = @id"
            DeleteCommand ="DELETE from elections where id = @id">

            <UpdateParameters>
                <asp:Parameter Name="title"/>
                <asp:Parameter Name="starttime" />
                <asp:Parameter Name="endtime"/>
                <asp:Parameter Name="descriptionelection"/>
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="id"/>
            </DeleteParameters>
        </asp:SqlDataSource>
            </div>
        </div>

    </form>
    <script src="Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="Scripts/materialize.min.js"></script>
    <script src="Scripts/init.js" type="text/javascript"></script>    
</body>
</html>
